/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jamie' at '30/11/17 11:11' with Gradle 3.0
 *
 * @author Jamie, @date 30/11/17 11:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
